openapi: 3.0.4
info:
  title: Sales Tax Lookup
  description: Sales Tax Lookup is a simple tool for looking up the sales tax rate of a location. It returns the sales tax rate.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/salestax:
    get:
      summary: Lookup Sales Tax of Zip Code
      description: Sales Tax Lookup is a simple tool for looking up the sales tax rate of a location. It returns the sales tax rate.
      operationId: salestax
      parameters:
      - name: zip
        in: query
        schema:
          type: string
        required: true
        description: The zip code for which you want to get the sales tax rate (e.g., 90210)
        example: '90210'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  state: CA
                  zip: 90210
                  region: WEST HOLLYWOOD TOURISM IMPROVEMENT DISTRICT
                  rate: 0.1025
                  county: 0.0025
                  city: 0.0075
                  special: 0.0325
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
